Fixed - the install script will keep running if the service is not available

diff --git a/install b/install
--- a/install
+++ b/install
@@ -37,12 +37,21 @@ kiwi_current_backup="/home/backup"
 
 function run_and_check() {
     local command_to_run="$1"    
-    $command_to_run    
-    if [ $? -eq 0 ]; then
+    $command_to_run
+    
+    local exit_code=$?
+
+    if [ $exit_code -eq 0 ]; then
         PrintGreen "Command $command_to_run succeeded"
     else
-        PrintRed "Command $command_to_run failed"
-        exit 1
+        PrintRed "Command $command_to_run failed with exit code $exit_code"
+        
+        if [ $exit_code -eq 5 ]; then
+            # Exit code 5 typically indicates that the service is not loaded
+            PrintRed "Warning: Service is not loaded or does not exist."
+        else
+            exit 1
+        fi
     fi
 }
 
